"""Eventbrite — public search API was deprecated in 2020 for new apps.

This adapter pulls Eventbrite's public location-based discovery RSS feed
(generated by their public listing pages). It is best-effort: layout/feed
URLs change over time and not every event is included. For a publishable
project, document this clearly and fall back to user-submitted Eventbrite
URLs when feed reliability dips.
"""
from __future__ import annotations

import logging
from typing import Iterator

import feedparser

from models import Event
from sources.base import Source
from utils.borough import detect_borough
from utils.dates import to_local_iso, to_utc_iso
from utils.http import get_text

log = logging.getLogger(__name__)
FEED_URLS = [
    "https://www.eventbrite.com/d/ny--new-york/events/rss/",
    "https://www.eventbrite.com/d/ny--brooklyn/events/rss/",
    "https://www.eventbrite.com/d/ny--queens/events/rss/",
    "https://www.eventbrite.com/d/ny--bronx/events/rss/",
    "https://www.eventbrite.com/d/ny--staten-island/events/rss/",
]


class EventbriteRSS(Source):
    name = "eventbrite_rss"

    def fetch(self) -> Iterator[Event]:
        for url in FEED_URLS:
            try:
                text = get_text(url)
            except Exception as e:  # noqa: BLE001
                log.warning("eventbrite_rss %s failed: %s", url, e)
                continue
            feed = feedparser.parse(text)
            for entry in feed.entries:
                yield Event(
                    source=self.name,
                    source_id=entry.get("id") or entry.get("link"),
                    title=entry.get("title", ""),
                    description=entry.get("summary", ""),
                    url=entry.get("link"),
                    start_utc=to_utc_iso(entry.get("published")),
                    start_local=to_local_iso(entry.get("published")),
                    borough=detect_borough(address=entry.get("summary", "")),
                    raw=dict(entry),
                )
